### ISSUE TITLE
NoneType can't be used in 'await' expression

### ISSUE THREAD

**Issue by JaxonYon** [GriffinG1/Cortana#1]
```
ExtensionFailed: Extension 'cogs.log' raised an error: TypeError: object NoneType can't be used in 'await' expression
```
Something seems to have broken

**Comment by GriffinG1** [comment]
`cogs.log` does not exist in this repository, it is a single file bot. Further, outside of linter, fstring, and variable name cleanups I haven't maintained this in over 2.5 years, meaning this will not work on latest versions of discord.py anyways.
